### ISSUE TITLE
Should this project use separate bin/lib?

### ISSUE THREAD

**Issue by gregschmit** [gregschmit/omake#10]
In my excitement of learning common patterns in Rust, I might have over-engineered this project. Currently it is separated into a `lib` crate and a `bin` crate, the idea being to separate concerns of core logic and frontend, and also so certain logic could be reused if another project wanted to, for example, make a different frontend to `omake`.

The problem I'm seeing is that I had to separate `Args` and `Opts` struct so the `lib` would not depend on `clap`, and this requires manual duplication of a handful of struct fields that must be kept in sync. Furthermore, sub-MAKE (related to #8) would need to know the command line options to execute and would need to know how the parent process was invoked, so it seems like a lot of the backend logic is tightly coupled to the binary aspect of this project.

I'm considering removing the `lib` crate and just making this project a single `bin` crate.

Thoughts?

@neonimp

**Comment by neonimp** [comment]
Also another benfit of a pure bin, i you don't have API concerns, as long as we are stable with the CLI everything else is implementation details that we are at will to alter. I also tend to go for a very sctrict and stable API even for libs, see [daemonize-me](https://github.com/neonimp/daemonize-me) for an example of what I mean, everything not in the main struct and accessors is implementation detail and subject to change.

**Comment by gregschmit** [comment]
Yeah I agree with everything you said.

**Comment by neonimp** [comment]
Want any help with this one?

**Comment by gregschmit** [comment]
I can handle this one.

**Comment by neonimp** [comment]
Ok, I will wait for you to finish this before picking up another issue, because this one is very much the definition of there would be conflicts.

**Comment by gregschmit** [comment]
Fixed in c7e86c126a14ff6828636af23bef1fac3ce2f4fd
