### ISSUE TITLE
Show offending line if context provided to log_warn or log_err.

### ISSUE THREAD

**Issue by gregschmit** [gregschmit/omake#2]
Perhaps use different colors for warn vs err? Probably should do colors only if a tty is detected.

I think `is-terminal` is the best current Rust solution for providing `isatty` functionality cross-platform?

**Comment by gregschmit** [comment]
Right now the logging system will show the line number, but we could easily go scan that line or just add the line content to the `Context` struct?

**Comment by neonimp** [comment]
> Right now the logging system will show the line number, but we could easily go scan that line or just add the line content to the `Context` struct?

aving the line number should be easy to read the line from the file again, or just clone the line into the struct.

**Comment by neonimp** [comment]
You can assign me to this one and the MAKE one

**Comment by neonimp** [comment]
I guess this one can be closed since merging #9

**Comment by gregschmit** [comment]
Re-opening because I didn't realize the line isn't actually printed out anywhere just stored in the struct. I also adjusted it to store the line in the struct while parsing, which while uses a little bit more memory, is much faster than re-reading the line during logging.
