### ISSUE TITLE
Create a project to track features implemented vs need to implement?

### ISSUE THREAD

**Issue by neonimp** [gregschmit/omake#7]
My suggestion is to create a github project to track progress on features and group issues under them, this should help anyone wishing to contribute pick a starting point.

Regards

**Comment by gregschmit** [comment]
This is a good idea; I just made one and this weekend I'll take some time to flesh it out.

**Comment by gregschmit** [comment]
I looked into this, however this project is not large enough to leverage the benefits of GitHub projects. I would rather use issues (assignment to declare who is working on that issue), and labels to tag good first issues.
